#!/bin/sh
hook_script_dir="$(dirname "$0")"
repo_root_dir=$(git rev-parse --show-toplevel)

# Get the list of files staged for commit, and exit early if there are none
files=$(git diff --cached --name-only)
if [[ -z $files ]]; then
	echo "No staged files"
	exit 0
fi

# Check if formatting should be skipped for any file extenions
IFS=',' read -ra skips <<< "$SYCDAN_SKIPFORMAT"
for ext in "${skips[@]}"; do
  declare "skipformat_$ext"=1
	echo "Formatting disabled for .$ext files"
done

# If CS formatting is enabled, check if CSharpier is installed
if [[ -z $skipformat_cs ]]; then
	# Attempt to get the version of CSharpier, swallowing any output
	dotnet csharpier --version &> /dev/null
	# Check if the above command failed (indicating the tool is not installed)
	if [ $? -ne 0 ]; then
		echo "Installing CSharpier"
		dotnet tool install -g csharpier
	fi
fi

# Iterate over all staged files
for file in $files; do
	# If the file was deleted, skip it
	if [[ ! -e "$repo_root_dir/$file" ]]; then
		continue
	fi
	# Format the file based on its extension, provided formatting is enabled for it
	if [[ -z $skipformat_cs && "$file" == *.cs ]]; then
		dotnet csharpier $file --config-path=$hook_script_dir/.csharpierrc.json
	fi
	# Re-stage the file
	git add "$file"
done
